### ISSUE TITLE
Problem statement

### ISSUE THREAD

**Issue by codehag** [tc39/proposal-destructuring-private#1]
Can you give a few sentences about what use cases this solves?

**Comment by jridgewell** [comment]
Closing with https://github.com/tc39/proposal-destructuring-private#motivation

**Comment by littledan** [comment]
This motivation seems a little thin to me to be honest. I like the general consistency, but that would be enhanced by being able to use private fields in objects in the expression context as well. I don't see what is gained vs referring to `this.#x` in expression context.

**Comment by bakkot** [comment]
> that would be enhanced by being able to use private fields in objects in the expression context as well

I don't actually think this would be an improvement in consistency (though I favor it for other reasons). Destructuring is about _reading_ properties, not creating them.
