### ISSUE TITLE
 Can private fields be accessed directly within a class?

### ISSUE THREAD

**Issue by mantou132** [tc39/proposal-destructuring-private#14]
This would allow us to omit a lot of this references, e.g.:

```ts
class MyElement extends HTMLElement {
  #state = createState({ a: 1, b: 2 });
  #render = () => {
    return html`<div>${#state.a} ${#state.b}</div>`;
  }
}
```

**Comment by jridgewell** [comment]
No, we explicitly decided to require the object when accessing a private field when discussing the original [private fields proposal](https://github.com/tc39/proposal-class-fields). This won't change with the destructuring proposal.
